import Search from '../pages/Search/Search';

export const ADMIN = '/admin';
export const LANDING = '/index';
export const HOME = '/home';
export const VIDEO = '/video';
export const PLAYER = `${VIDEO}/player`;
export const PROFILE = '/profile';
export const PROFILE_MY_LIST = `${PROFILE}/my_list`;
export const PROFILE_MY_UPLOADS = `${PROFILE}/my_uploads`;
export const PROFILE_MY_EVENTS = `${PROFILE}/my_events`;
export const UPLOAD = '/upload';
export const SIGN_IN = '/sign_in';
export const SIGN_UP = '/sign_up';
export const SEARCH = '/search';
export const SEARCH_ALL = `${SEARCH}/all`;
export const SEARCH_VIDEOS = `${SEARCH}/videos`;
export const SEARCH_USERS = `${SEARCH}/users`;
export const SEARCH_DISCIPLINES = `${SEARCH}/disciplines`;
export const EVENT = '/event';
export const CATEGORY = '/category';
export const RESTRICTED_AREA = '/restricted_area';
export const DISCOVER = '/discover';
export const DOCUMENTATION = '/documentation';